# Generated by Django 5.2.3 on 2025-06-21 01:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PptTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="생성일시"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="수정일시"),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="템플릿 이름"
                    ),
                ),
                (
                    "template_file",
                    models.FileField(
                        upload_to="ppt_templates/", verbose_name="템플릿 파일 (.pptx)"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="활성화 여부"),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="템플릿 설명"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="ppt_templates",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="등록자",
                    ),
                ),
            ],
            options={
                "verbose_name": "PPT 템플릿",
                "verbose_name_plural": "PPT 템플릿",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="WorshipInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="생성일시"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="수정일시"),
                ),
                (
                    "worship_date",
                    models.DateField(unique=True, verbose_name="예배 날짜"),
                ),
                (
                    "worship_type",
                    models.CharField(
                        choices=[
                            ("sunday_am", "주일 오전 예배"),
                            ("sunday_pm", "주일 오후 예배"),
                            ("wednesday", "수요 예배"),
                            ("friday", "금요 철야 예배"),
                            ("dawn", "새벽 예배"),
                            ("other", "기타 예배"),
                        ],
                        default="sunday_am",
                        max_length=20,
                        verbose_name="예배 종류",
                    ),
                ),
                (
                    "speaker",
                    models.CharField(blank=True, max_length=100, verbose_name="설교자"),
                ),
                (
                    "sermon_title",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="설교 제목"
                    ),
                ),
                (
                    "sermon_scripture",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="설교 본문"
                    ),
                ),
                (
                    "announcements",
                    models.TextField(blank=True, verbose_name="광고 내용"),
                ),
                (
                    "prayer_topic",
                    models.TextField(blank=True, verbose_name="기도 제목"),
                ),
                ("notes", models.TextField(blank=True, verbose_name="추가 비고")),
                (
                    "is_llm_processed",
                    models.BooleanField(default=False, verbose_name="LLM 처리 여부"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="worship_infos",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="등록자",
                    ),
                ),
            ],
            options={
                "verbose_name": "예배 정보",
                "verbose_name_plural": "예배 정보",
                "ordering": ["-worship_date", "worship_type"],
            },
        ),
        migrations.CreateModel(
            name="PptRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="생성일시"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="수정일시"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "대기 중"),
                            ("processing", "제작 중"),
                            ("completed", "제작 완료"),
                            ("failed", "제작 실패"),
                            ("no_song_info", "찬양 정보 없음"),
                            ("no_worship_info", "예배 정보 없음"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="제작 상태",
                    ),
                ),
                (
                    "generated_ppt_file",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="ppts/",
                        verbose_name="생성된 PPT 파일",
                    ),
                ),
                (
                    "celery_task_id",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Celery 작업 ID",
                    ),
                ),
                (
                    "progress_message",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="진행 상황 메시지"
                    ),
                ),
                (
                    "completed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="완료 일시"
                    ),
                ),
                (
                    "requested_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="ppt_requests",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="요청자",
                    ),
                ),
                (
                    "worship_info",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ppt_request",
                        to="core.worshipinfo",
                        verbose_name="연결된 예배 정보",
                    ),
                ),
            ],
            options={
                "verbose_name": "PPT 제작 요청",
                "verbose_name_plural": "PPT 제작 요청",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="SongInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="생성일시"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="수정일시"),
                ),
                ("order", models.PositiveIntegerField(verbose_name="찬양 순서")),
                ("title", models.CharField(max_length=200, verbose_name="찬양 제목")),
                (
                    "youtube_url",
                    models.URLField(
                        blank=True, max_length=500, verbose_name="찬양 영상 URL"
                    ),
                ),
                ("lyrics", models.TextField(blank=True, verbose_name="전체 찬양 가사")),
                (
                    "lyrics_pages",
                    models.JSONField(
                        blank=True, default=list, verbose_name="페이지별 가사"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="song_infos",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="등록자",
                    ),
                ),
                (
                    "worship_info",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="song_infos",
                        to="core.worshipinfo",
                        verbose_name="연결된 예배 정보",
                    ),
                ),
            ],
            options={
                "verbose_name": "찬양 정보",
                "verbose_name_plural": "찬양 정보",
                "ordering": ["worship_info__worship_date", "order"],
                "unique_together": {("worship_info", "order")},
            },
        ),
    ]
