# Generated by Django 5.2.3 on 2025-06-21 02:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="songinfo",
            options={
                "ordering": ["worship_info__worship_date", "order", "is_ending_song"],
                "verbose_name": "찬양 정보",
                "verbose_name_plural": "찬양 정보",
            },
        ),
        migrations.AlterUniqueTogether(
            name="songinfo",
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name="worshipinfo",
            name="announcements",
        ),
        migrations.RemoveField(
            model_name="worshipinfo",
            name="prayer_topic",
        ),
        migrations.AddField(
            model_name="songinfo",
            name="is_ending_song",
            field=models.BooleanField(default=False, verbose_name="결단 찬양 여부"),
        ),
        migrations.AddField(
            model_name="worshipinfo",
            name="ads_manager",
            field=models.CharField(
                blank=True, max_length=100, verbose_name="광고 담당자"
            ),
        ),
        migrations.AddField(
            model_name="worshipinfo",
            name="benediction_minister",
            field=models.CharField(blank=True, max_length=100, verbose_name="축도자"),
        ),
        migrations.AddField(
            model_name="worshipinfo",
            name="main_prayer_topic",
            field=models.TextField(blank=True, verbose_name="예배 기도 제목"),
        ),
        migrations.AddField(
            model_name="worshipinfo",
            name="offering_minister",
            field=models.CharField(blank=True, max_length=100, verbose_name="봉헌자"),
        ),
        migrations.AddField(
            model_name="worshipinfo",
            name="prayer_minister",
            field=models.CharField(blank=True, max_length=100, verbose_name="기도자"),
        ),
        migrations.AddField(
            model_name="worshipinfo",
            name="worship_announcements",
            field=models.JSONField(blank=True, default=list, verbose_name="광고 목록"),
        ),
        migrations.AlterField(
            model_name="pptrequest",
            name="requested_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="ppt_requests_created",
                to=settings.AUTH_USER_MODEL,
                verbose_name="요청자",
            ),
        ),
        migrations.AlterField(
            model_name="ppttemplate",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="ppt_templates_created",
                to=settings.AUTH_USER_MODEL,
                verbose_name="등록자",
            ),
        ),
        migrations.AlterField(
            model_name="songinfo",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="song_infos_created",
                to=settings.AUTH_USER_MODEL,
                verbose_name="등록자",
            ),
        ),
        migrations.AlterField(
            model_name="worshipinfo",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="worship_infos_created",
                to=settings.AUTH_USER_MODEL,
                verbose_name="등록자",
            ),
        ),
        migrations.AlterField(
            model_name="worshipinfo",
            name="sermon_scripture",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="설교 본문 범위"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="songinfo",
            unique_together={("worship_info", "order", "is_ending_song")},
        ),
    ]
