# Generated by Django 5.2.3 on 2025-06-21 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_alter_songinfo_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="worshipinfo",
            name="worship_type",
            field=models.CharField(
                choices=[("youth_4th", "4부 예배 (청년 예배)")],
                default="youth_4th",
                max_length=20,
                verbose_name="예배 종류",
            ),
        ),
    ]
