# Generated by Django 5.2.3 on 2025-06-24 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_alter_worshipinfo_ads_manager_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="songinfo",
            name="youtube_url",
        ),
        migrations.AddField(
            model_name="songinfo",
            name="source_url",
            field=models.URLField(
                blank=True, max_length=500, verbose_name="가사 출처 URL"
            ),
        ),
    ]
