# Generated by Django 5.2.3 on 2025-06-25 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_remove_songinfo_youtube_url_songinfo_source_url"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="songinfo",
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name="songinfo",
            name="order",
            field=models.PositiveIntegerField(default=0, verbose_name="찬양 순서"),
        ),
    ]
