# Generated by Django 5.2.3 on 2025-06-25 01:59

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_alter_songinfo_unique_together_alter_songinfo_order"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="songinfo",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_ending_song", False)),
                fields=("worship_info", "order"),
                name="unique_normal_song_order_per_worship",
            ),
        ),
        migrations.AddConstraint(
            model_name="songinfo",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_ending_song", True)),
                fields=("worship_info",),
                name="unique_ending_song_per_worship",
            ),
        ),
    ]
